sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t prashantbhat84/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true prashantbhat84/docker-react npm run test
