sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t prashantbhat84/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true prashantbhat84/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-359929821378"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
